import type { Case } from "../types";
import {
  DnaIcon,
  BulletIcon,
  FabricIcon,
  FootprintIcon,
  FlaskIcon,
  GunIcon,
  CctvIcon,
  FingerprintIcon,
} from "../components/icons";

export const murderAtDock17: Case = {
  id: "case-01",
  title: "Murder at Dock 17",
  thumbnail: "https://picsum.photos/seed/dock17/400/200",
  brief:
    "A dock foreman was found dead in Warehouse 3 after a late-night shipment. Witnesses heard a single gunshot, then saw two figures fleeing into the fog. Detectives have brought you 12 pieces of evidence to process in your lab.",
  locked: false,
  puzzleUnlockStrategy: "all",
  suspects: [
    {
      name: "Marco Vance",
      description: "Dockworker with a violent past.",
      img: "https://picsum.photos/seed/marco/100/100",
    },
    {
      name: "Dana Cross",
      description: "Local gang affiliate, owns a registered .45 ACP.",
      img: "https://picsum.photos/seed/dana/100/100",
    },
    {
      name: "Liam Frost",
      description: "Security guard on duty the night of the murder.",
      img: "https://picsum.photos/seed/liam/100/100",
    },
  ],
  puzzles: [
    {
      id: "puz-01",
      name: "DNA Match",
      puzzleType: "DNA_MATCH",
      description: "Align DNA fragments to identify owner.",
      img: "https://picsum.photos/seed/glove/200/200",
      icon: DnaIcon,
      matchResult: "Glove DNA Match: Marco Vance",
    },
    {
      id: "puz-02",
      name: "Ballistics",
      puzzleType: "BALLISTICS",
      description: "Match firing pin marks to registered weapon.",
      img: "https://picsum.photos/seed/casing/200/200",
      icon: BulletIcon,
      matchResult: "Match: Dana Cross's .45 ACP",
    },
    {
      id: "puz-03",
      name: "Fiber Analysis",
      puzzleType: "FIBER_ANALYSIS",
      description: "Match fiber weave to suspect clothing.",
      img: "https://picsum.photos/seed/fabric/200/200",
      icon: FabricIcon,
      matchResult: "Torn fabric matches: Marco Vance's Jacket",
    },
    {
      id: "puz-04",
      name: "Footwear Impression",
      puzzleType: "FOOTWEAR_IMPRESSION",
      description: "Analyze tread pattern and size.",
      img: "https://picsum.photos/seed/shoeprint/200/200",
      icon: FootprintIcon,
      matchResult: "Analysis: Size 11 Work Boot",
    },
    {
      id: "puz-05",
      name: "DNA Gender Analysis",
      puzzleType: "DNA_GENDER",
      description: "Analyze sex chromosomes to determine gender.",
      img: "https://picsum.photos/seed/powder/200/200",
      icon: DnaIcon,
      matchResult: "Gender Analysis: Male",
    },
    {
      id: "puz-06",
      name: "DNA Ancestry Profile",
      puzzleType: "DNA_ANCESTRY",
      description: "Compare genetic markers to determine ancestry.",
      img: "https://picsum.photos/seed/knife/200/200",
      icon: DnaIcon,
      matchResult: "Ancestry Profile: European",
    },
    {
      id: "puz-07",
      name: "Blood Type Analysis",
      puzzleType: "BLOOD_TYPE_ANALYSIS",
      description: "Test blood sample to determine ABO and Rh type.",
      img: "https://picsum.photos/seed/audio/200/200",
      icon: FlaskIcon,
      matchResult: "Blood Type: A+",
    },
    {
      id: "puz-08",
      name: "Gunpowder Residue Test (GSR)",
      puzzleType: "PLACEHOLDER",
      description: "Detect recent firearm discharge.",
      img: "https://picsum.photos/seed/jacket/200/200",
      icon: GunIcon,
      matchResult: "Positive: Dana Cross",
    },
    {
      id: "puz-09",
      name: "CCTV Frame Reconstruction",
      puzzleType: "CCTV_RECONSTRUCTION",
      description: "Reassemble the scrambled video still.",
      img: "https://picsum.photos/seed/cctv-hoodie/300/300?grayscale&blur=1",
      icon: CctvIcon,
      matchResult: "Analysis: 5'10\"-6'0\"",
    },
    {
      id: "puz-10",
      name: "Fiber Analysis V2",
      puzzleType: "FIBER_ANALYSIS_V2",
      description:
        "Calibrate the spectrometer by matching the evidence waveform.",
      img: "https://picsum.photos/seed/scarf-fiber/200/200",
      icon: FabricIcon,
      matchResult: "Hidden Dye Signature: Green",
    },
    {
      id: "puz-11",
      name: "Ballistics Analysis V2",
      puzzleType: "BALLISTICS_V2",
      description:
        "Compare evidence to registered samples to determine if the firearm is in the database.",
      img: "https://picsum.photos/seed/casing-v2/200/200",
      icon: BulletIcon,
      matchResult: "Conclusion: Firearm is unregistered",
    },
    {
      id: "puz-12",
      name: "Residue on Smudge",
      puzzleType: "CHEMICAL_ANALYSIS",
      description: "Analyze a chemical residue found on a smudge mark.",
      img: "https://picsum.photos/seed/powder/200/200",
      icon: FlaskIcon,
      matchResult: "Traces of potting soil & floral preservative",
    },
    {
      id: "puz-13",
      name: "Partial Fingerprint",
      puzzleType: "FINGERPRINT_ANALYSIS",
      description: "Match a partial print against event access records.",
      img: "https://picsum.photos/seed/fingerprint/200/200",
      icon: FingerprintIcon,
      matchResult: "Fingerprint matches vendor/event access records",
    },
  ],
};
