import type { Case } from "../types";
import {
  FlaskIcon,
  FootprintIcon,
  CctvIcon,
  FabricIcon,
  SoundWaveIcon,
  BulletIcon,
  FingerprintIcon,
} from "../components/icons";

export const case02: Case = {
  id: "case-02",
  title: "The Midnight Heist",
  thumbnail: "https://picsum.photos/seed/case02/400/200",
  brief:
    "A priceless emerald was stolen from the city museum during a blackout. The thief left traces — can you identify them before they disappear into the night?",
  locked: false, // Unlocked to be playable
  puzzleUnlockStrategy: "all",
  analysisLimit: 5,
  culprit: "Tina Moore",
  suspects: [
    {
      name: "Tina Moore",
      description: "Florist",
      img: "https://firebasestorage.googleapis.com/v0/b/genai-assets.appspot.com/o/images%2Fsuspect_1.jpeg?alt=media",
      bloodType: "O+",
      shoeSize: 8,
      height: "5’6”",
      weight: "140 lbs",
      gunOwner: false,
      toneOfVoice: "Low-Pitched",
      connectionToScene: "Provided floral arrangements for a past museum gala",
      financialStanding: "Low",
    },
    {
      name: "Maria Lee",
      description: "Accountant",
      img: "https://firebasestorage.googleapis.com/v0/b/genai-assets.appspot.com/o/images%2Fsuspect_6.jpeg?alt=media",
      bloodType: "A+",
      shoeSize: 8,
      height: "5’4”",
      weight: "125 lbs",
      gunOwner: false,
      toneOfVoice: "High-Pitched",
      connectionToScene: "Attended a public lecture event at the museum",
      financialStanding: "Medium",
    },
    {
      name: "Peter Chan",
      description: "Security Guard",
      img: "https://firebasestorage.googleapis.com/v0/b/genai-assets.appspot.com/o/images%2Fsuspect_3.jpeg?alt=media",
      bloodType: "B-",
      shoeSize: 9,
      height: "5’9”",
      weight: "160 lbs",
      gunOwner: true,
      toneOfVoice: "Low-Pitched",
      connectionToScene: "Former part-time security staff at the museum",
      financialStanding: "High",
    },
    {
      name: "Grace Liu",
      description: "Gardener",
      img: "https://firebasestorage.googleapis.com/v0/b/genai-assets.appspot.com/o/images%2Fsuspect_8.jpeg?alt=media",
      bloodType: "O-",
      shoeSize: 6,
      height: "5’2”",
      weight: "115 lbs",
      gunOwner: false,
      toneOfVoice: "Low-Pitched",
      connectionToScene: "Supplied plants for a temporary botanical exhibit",
      financialStanding: "Low",
    },
    {
      name: "Mark Smith",
      description: "Jeweler / Museum Vendor",
      img: "https://firebasestorage.googleapis.com/v0/b/genai-assets.appspot.com/o/images%2Fsuspect_5.jpeg?alt=media",
      bloodType: "O+",
      shoeSize: 10,
      height: "5’11”",
      weight: "175 lbs",
      gunOwner: true,
      toneOfVoice: "Low-Pitched",
      connectionToScene:
        "Provided gemstone appraisals for the museum gift shop",
      financialStanding: "Medium",
    },
    {
      name: "Olivia Brooks",
      description: "Artist",
      img: "https://firebasestorage.googleapis.com/v0/b/genai-assets.appspot.com/o/images%2Fsuspect_4.jpeg?alt=media",
      bloodType: "AB+",
      shoeSize: 8,
      height: "5’7”",
      weight: "150 lbs",
      gunOwner: false,
      toneOfVoice: "Low-Pitched",
      connectionToScene:
        "Featured in a local artist showcase hosted in the museum atrium",
      financialStanding: "Low",
    },
    {
      name: "Adam Ross",
      description: "Lawyer",
      img: "https://firebasestorage.googleapis.com/v0/b/genai-assets.appspot.com/o/images%2Fsuspect_7.jpeg?alt=media",
      bloodType: "A-",
      shoeSize: 8,
      height: "5’10”",
      weight: "165 lbs",
      gunOwner: false,
      toneOfVoice: "Low-Pitched",
      connectionToScene: "Donated to the museum’s annual fundraising auction",
      financialStanding: "High",
    },
    {
      name: "Rachel Kim",
      description: "Photographer",
      img: "https://firebasestorage.googleapis.com/v0/b/genai-assets.appspot.com/o/images%2Fsuspect_2.jpeg?alt=media",
      bloodType: "O+",
      shoeSize: 9,
      height: "5’8”",
      weight: "160 lbs",
      gunOwner: false,
      toneOfVoice: "Low-Pitched",
      connectionToScene: "Hired to photograph a previous exhibition opening",
      financialStanding: "Medium",
    },
  ],
  puzzles: [
    {
      id: "puz-c2-01",
      name: "Blood Type Analysis",
      puzzleType: "BLOOD_TYPE_ANALYSIS",
      description: "Test blood sample to determine ABO and Rh type.",
      img: "https://picsum.photos/seed/blood-c2/200/200",
      icon: FlaskIcon,
      matchResult: "Blood type O+",
    },
    {
      id: "puz-c2-02",
      name: "Footwear Impression",
      puzzleType: "FOOTWEAR_IMPRESSION",
      description: "Analyze tread pattern and size.",
      img: "https://picsum.photos/seed/shoe-c2/200/200",
      icon: FootprintIcon,
      matchResult: "Shoe size 8",
    },
    {
      id: "puz-c2-03",
      name: "CCTV Frame Reconstruction",
      puzzleType: "CCTV_RECONSTRUCTION",
      description: "Reassemble the scrambled video still.",
      img: "https://picsum.photos/seed/cctv-c2/300/300?grayscale&blur=1",
      icon: CctvIcon,
      matchResult: "Height between 5’6”–5’8”",
    },
    {
      id: "puz-c2-04",
      name: "Fiber Analysis V2",
      puzzleType: "FIBER_ANALYSIS_V2",
      description:
        "Calibrate the spectrometer by matching the evidence waveform.",
      img: "https://picsum.photos/seed/fiber-c2/200/200",
      icon: FabricIcon,
      matchResult: "Green",
    },
    {
      id: "puz-c2-05",
      name: "Audio Spectrogram",
      puzzleType: "PLACEHOLDER",
      description: "Analyze audio frequency and patterns.",
      img: "https://picsum.photos/seed/audio-c2/200/200",
      icon: SoundWaveIcon,
      matchResult: "Low-pitched",
    },
    {
      id: "puz-c2-06",
      name: "Ballistics Analysis V2",
      puzzleType: "BALLISTICS_V2",
      description:
        "Compare evidence to registered samples to determine if the firearm is in the database.",
      img: "https://picsum.photos/seed/ballistics-c2/200/200",
      icon: BulletIcon,
      matchResult: "Not a registered gun owner",
    },
    {
      id: "puz-c2-07",
      name: "Residue on Smudge",
      puzzleType: "CHEMICAL_ANALYSIS",
      description: "Analyze a chemical residue found on a smudge mark.",
      img: "https://picsum.photos/seed/powder/200/200",
      icon: FlaskIcon,
      matchResult: "Traces of potting soil & floral preservative",
    },
    {
      id: "puz-c2-08",
      name: "Partial Fingerprint",
      puzzleType: "FINGERPRINT_ANALYSIS",
      description: "Match a partial print against event access records.",
      img: "https://picsum.photos/seed/fingerprint/200/200",
      icon: FingerprintIcon,
      matchResult: "Fingerprint matches vendor/event access records",
    },
  ],
};
